//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace ClasesForCatanGame
{
	public class City
	{
		private Hex[] hexes;
		private Vector3 position;
		private int k; // коэфициент усиления для населеного пункта для поселения 1 для города 2 можно сделать будевой в принципе
		public int K {	get{return k;}	}// чтобы читать к


		public City (Hex[] hexesOfCity, Vector3 positionOfCity)
		{// так как город не может появиться самостоятельно а только превратиться из поселения
		// то тогда при иницилизации всегда точно будет поселение
			hexes = hexesOfCity;
			position = positionOfCity;
			k = 1;
		}
		
		public void	 MakeMeTown(){
			k = 2;
		}

		public string[] GetResourcesOnDiceNum(int diceNum){
			int i=0;
			foreach (Hex hex in hexes) {
				if (hex.Number() == diceNum && !hex.isRobberHere()) i++;
			}
			string[] resources = new string[i];
			foreach (Hex hex in hexes) {
				if (hex.Number() == diceNum && !hex.isRobberHere()) 
					resources.SetValue(hex.Resource(),resources.Length);
			}
			return resources;
		}



	}
}

