//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace ClasesForCatanGame
{
	public class Player
	{
		bool isItI; // для сетки
		bool isItMyTurn;
		bool maxRoad;
		bool maxKnight;
		int victoryPoint;

		List<City> Cities;
		//list<Road>
		//list hand


		public Player ()
		{
		}

		public void SetRoad();
		public void SetTown();
		public int CountVictoryPoint();
		public void RemoveHandOnHalf();



		/*
		set road(vect0r
		 * /
	}
}

