//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace ClasesForCatanGame
{
	public class Road
	{
		protected Vector3 to, from;

		public Road (Vector3 vecorTo, Vector3 vectorFrom)
		{// нужна проверка на vecorTo = vectorFrom
			to = vecorTo;
			from = vectorFrom;
		}

		public Vector3 Position(){
			return (to + (from - to) / 2);
		}
	
		public Quaternion Rotation(){
			return Quaternion.FromToRotation(to + (from-to)/2,to);
		}

	}
}

